version: "3"

services:
    webapp:
        build: .
        ports:
            - 3000:3000
    mongo:
        image: mongo
        volumes:
            - mongo-volume:/data/db

volumes:
    mongo-volume:
